// <auto-generated />
namespace ShipBob.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requiredpropsonOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredpropsonOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201709190349435_required props on Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
